[project]
name = "website-builder"
version = "0.1.0"
description = "Build script for personal website"
requires-python = ">=3.8"
dependencies = [
    "markdown>=3.4"
]

[tool.uv]
dev-dependencies = []